import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';

const db=new PGlite();
const admin='00000000-0000-4000-8000-000000000099';
const uid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
let checks=0;
async function ok(sql,params=[]){checks++;return db.query(sql,params);}
async function rejects(sql,params=[],pattern){checks++;await assert.rejects(db.query(sql,params),pattern);}
try{
  // These are schema-only test fixtures based on the inspected production tables.
  // No production data or secrets are copied into this local database.
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create schema storage; create schema ot_test;
    create table auth.users(id uuid primary key);
    create table public.admins(user_id uuid primary key references auth.users(id),created_at timestamptz default now());
    create table public.members(id bigint primary key,name text not null,role text,auth_user_id uuid,is_active boolean default true);
    create table public.ot_reviews(
      id bigint generated by default as identity primary key,created_at timestamptz default now(),updated_at timestamptz default now(),
      candidate_name text not null check(char_length(candidate_name) between 1 and 60),somoim_nickname text not null check(char_length(somoim_nickname) between 1 and 80),
      room_label text not null default 'OT Room',video_source text not null,video_url text,video_file_path text,video_file_name text,memo text,
      status text not null default 'IN_REVIEW' check(status in ('IN_REVIEW','APPROVED','REJECTED')),
      due_at timestamptz not null,eligible_operator_ids bigint[] not null,required_majority smallint not null check(required_majority>0),created_by uuid,resolved_at timestamptz,
      check((video_source='LINK' and video_url is not null and video_file_path is null) or (video_source='FILE' and video_file_path is not null and video_url is null))
    );
    create table public.ot_review_votes(
      id bigint generated by default as identity primary key,created_at timestamptz default now(),updated_at timestamptz default now(),
      review_id bigint not null references public.ot_reviews(id) on delete cascade,voter_member_id bigint not null references public.members(id),
      decision text not null check(decision in ('APPROVE','REJECT','HOLD')),unique(review_id,voter_member_id)
    );
    create table storage.buckets(id text primary key,public boolean not null);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text,metadata jsonb);
    insert into storage.buckets values('ot-review-videos',false);
    grant usage on schema public,auth,storage to service_role;
    grant all on all tables in schema public,auth,storage to service_role;
    grant usage,select on all sequences in schema public to service_role;
    create table ot_test.clock(now_at timestamptz);
    insert into ot_test.clock values('2026-10-07T00:00:00Z');
    create function ot_test.clock_timestamp() returns timestamptz language sql volatile as 'select now_at from ot_test.clock';
    grant usage on schema ot_test to service_role; grant select on ot_test.clock to service_role; grant execute on function ot_test.clock_timestamp() to service_role;
  `);
  await db.query('insert into auth.users(id) values($1)',[admin]);
  await db.query('insert into public.admins(user_id) values($1)',[admin]);
  for(let n=1;n<=8;n++){
    await db.query('insert into auth.users(id) values($1)',[uid(n)]);
    await db.query('insert into public.members(id,name,role,auth_user_id) values($1,$2,$3,$4)',[n,'fixture-'+n,n<=7?'운영진':'모임원',uid(n)]);
  }
  const migration=await readFile(new URL('../supabase/migrations/20261007010721_ot_room_private_invites.sql',import.meta.url),'utf8');
  await db.exec(migration);checks++;
  assert.equal((await ok('select count(*)::int as count from public.ot_room_operator_access')).rows[0].count,0,'legacy role/account links must not auto-grant OT access');
  // Simulate the explicit administrator grants used by the production UI.
  await db.query('insert into public.ot_room_operator_access(user_id,member_id,granted_by) select auth_user_id,id,$1 from public.members where role=$2',[admin,'운영진']);
  // Install the exact migration first. Only its clock dependency is then replaced
  // locally so the same SQL body can exercise opening/closing boundaries at any hour.
  for(const signature of ['public.vom_ot_finalize_upload(uuid,uuid,text,text,text,text)','public.vom_ot_record_vote(bigint,bigint,text,uuid)']){
    const {rows}=await db.query('select pg_get_functiondef($1::regprocedure) as definition',[signature]);
    await db.exec(rows[0].definition.replaceAll('clock_timestamp()','ot_test.clock_timestamp()'));
  }
  const invite='e2c5c72d-631e-4022-b405-2e1e02480533';
  const claim='f492568c-83a0-4e40-84c4-88e073890b05';
  const path='reviews/'+invite+'/'+claim+'.mp4';
  await db.query('insert into public.ot_room_invites(id,token_hash,issued_by,expires_at,upload_claim_id,upload_claimed_at) values($1,$2,$3,$4,$5,$6)',[invite,'a'.repeat(64),admin,'2099-10-09T00:00:00Z',claim,'2026-10-07T00:00:00Z']);
  const args=[invite,claim,'new candidate','somoim nickname',path,'video.mp4'];
  const finalize='select public.vom_ot_finalize_upload($1,$2,$3,$4,$5,$6) as result';
  await db.exec('set role service_role');
  await rejects(finalize,args,/video_missing/);
  await db.exec('reset role');
  await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)', ['ot-review-videos',path,{size:24,mimetype:'video/mp4'}]);
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T09:00:00Z']);
  await db.exec('set role service_role');
  await rejects(finalize,args,/room_closed/);
  assert.equal((await ok('select count(*)::int as count from public.ot_reviews')).rows[0].count,0);
  await db.exec('reset role');
  await db.query('update ot_test.clock set now_at=$1',['2026-10-06T23:59:59Z']);
  await db.exec('set role service_role');
  await rejects(finalize,args,/room_closed/);
  await db.exec('reset role');
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T00:00:00Z']);
  await db.exec('set role service_role');
  await rejects(finalize,[invite,uid(20),...args.slice(2)],/invalid_claim/);
  await rejects(finalize,[invite,null,...args.slice(2)],/invalid_claim/);
  await rejects(finalize,[...args.slice(0,4),'reviews/other/video.mp4','video.mp4'],/invalid_file_path/);
  const reviewId=(await ok(finalize,args)).rows[0].result.id;
  const stored=(await ok('select * from public.ot_reviews where id=$1',[reviewId])).rows[0];
  assert.equal(stored.required_majority,4);assert.deepEqual(stored.eligible_operator_ids,[1,2,3,4,5,6,7]);assert.equal(stored.somoim_nickname,'somoim nickname');
  assert.equal((await ok('select review_id,upload_claim_id from public.ot_room_invites where id=$1',[invite])).rows[0].review_id,reviewId);
  await rejects(finalize,args,/already_submitted/);
  const vote='select public.vom_ot_record_vote($1,$2,$3,$4) as result';
  await rejects(vote,[reviewId,2,'APPROVE',uid(1)],/voter_identity_mismatch/);
  await rejects(vote,[reviewId,8,'APPROVE',admin],/operator_required/);
  await ok(vote,[reviewId,1,'APPROVE',uid(1)]);
  await ok(vote,[reviewId,1,'HOLD',uid(1)]);
  assert.equal((await ok('select count(*)::int as count from public.ot_review_votes where review_id=$1',[reviewId])).rows[0].count,1);
  await ok(vote,[reviewId,1,'APPROVE',uid(1)]);
  await ok(vote,[reviewId,2,'APPROVE',uid(2)]);
  await ok(vote,[reviewId,3,'APPROVE',uid(3)]);
  const resolved=(await ok(vote,[reviewId,4,'APPROVE',admin])).rows[0].result;
  assert.equal(resolved.status,'APPROVED');assert.equal(resolved.approval_count,4);
  await rejects(vote,[reviewId,5,'REJECT',uid(5)],/review_resolved/);
  assert.equal((await ok('select count(*)::int as count from public.members')).rows[0].count,8,'voting must not create a member automatically');
  await db.exec('reset role; set role anon');
  await rejects('select * from public.ot_room_invites',[],/permission denied/);
  await rejects('select * from public.ot_room_operator_access',[],/permission denied/);
  await rejects(finalize,args,/permission denied/);
  await db.exec('reset role; set role authenticated');
  await rejects('select * from public.ot_room_invites',[],/permission denied/);
  await rejects(vote,[reviewId,1,'APPROVE',uid(1)],/permission denied/);
  await db.exec('reset role');
  const functions=(await db.query("select proname,prosecdef,proconfig from pg_proc where proname in ('vom_ot_finalize_upload','vom_ot_record_vote')")).rows;
  assert(functions.every(fn=>fn.prosecdef===false));checks++;
  console.log('PostgreSQL migration and security checks passed:',checks);
}finally{await db.close();}
