import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';

const db=new PGlite();
const admin='00000000-0000-4000-8000-000000000099';
const uid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
let checks=0;
async function ok(sql,params=[]){checks++;return db.query(sql,params);}
async function rejects(sql,params=[],pattern){checks++;await assert.rejects(db.query(sql,params),pattern);}
try{
  // These are schema-only test fixtures based on the inspected production tables.
  // No production data or secrets are copied into this local database.
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create schema storage; create schema ot_test; create schema private;
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema public,auth to anon,authenticated;
    create table auth.users(id uuid primary key);
    create table public.vom_push_invites(id bigint primary key,invite_token text,is_active boolean);
    create table public.vom_push_subscriptions(id bigint primary key,invite_id bigint references public.vom_push_invites(id));
    insert into public.vom_push_invites values(1,repeat('a',43),true);
    insert into public.vom_push_subscriptions values(1,1);
    create table public.admins(user_id uuid primary key references auth.users(id),created_at timestamptz default now());
    create table public.members(id bigint generated by default as identity primary key,name text not null unique,role text,auth_user_id uuid,is_active boolean default true,
      created_at timestamptz default now(),nickname text,profile_image_url text,joined_at date,birth_date date,region text,gender text,favorite_singers text,join_order integer,job text,phone text);
    create table public.member_account_settings(member_id bigint primary key references public.members(id),must_change_password boolean default false,password_changed_at timestamptz,password_hint text);
    alter table public.members enable row level security;
    create policy "members public profile read" on public.members for select to anon,authenticated using(true);
    create policy "admins can read members" on public.members for select to authenticated using(exists(select 1 from public.admins where user_id=auth.uid()));
    grant select on public.members,public.admins to anon,authenticated;
    create view public.members_public with(security_invoker=true,security_barrier=true) as select id,created_at,name,nickname,profile_image_url,joined_at,is_active,role,birth_date,region,gender,favorite_singers,join_order,job from public.members;
    grant select on public.members_public to anon,authenticated;
    create table public.events(id bigint primary key,created_at timestamptz,title text,event_type text,event_date date,start_time time,end_time time,location text,location_id bigint,image_url text,somoim_apply_enabled boolean,somoim_apply_url text,host_note text,description text,somoim_open_at timestamptz,somoim_open_enabled boolean);
    alter table public.events enable row level security;
    create policy "everyone can read events" on public.events for select to anon,authenticated using(true);
    grant select on public.events to anon,authenticated;
    create table public.ot_reviews(
      id bigint generated by default as identity primary key,created_at timestamptz default now(),updated_at timestamptz default now(),
      candidate_name text not null check(char_length(candidate_name) between 1 and 60),somoim_nickname text not null check(char_length(somoim_nickname) between 1 and 80),
      room_label text not null default 'OT Room' check(room_label in('OT Room','OT Room 1','OT Room 2','별도 안내')),video_source text not null,video_url text,video_file_path text,video_file_name text,memo text,
      status text not null default 'IN_REVIEW' check(status in ('IN_REVIEW','APPROVED','REJECTED')),
      due_at timestamptz not null,eligible_operator_ids bigint[] not null,required_majority smallint not null check(required_majority>0),created_by uuid,resolved_at timestamptz,
      check((video_source='LINK' and video_url is not null and video_file_path is null) or (video_source='FILE' and video_file_path is not null and video_url is null))
    );
    create table public.ot_review_votes(
      id bigint generated by default as identity primary key,created_at timestamptz default now(),updated_at timestamptz default now(),
      review_id bigint not null references public.ot_reviews(id) on delete cascade,voter_member_id bigint not null references public.members(id),
      decision text not null check(decision in ('APPROVE','REJECT','HOLD')),unique(review_id,voter_member_id)
    );
    create table storage.buckets(id text primary key,public boolean not null,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text,metadata jsonb);
    insert into storage.buckets values('ot-review-videos',false,array['video/mp4','audio/mp4','audio/mpeg','audio/aac','audio/wav']);
    grant usage on schema public,auth,storage to service_role;
    grant all on all tables in schema public,auth,storage to service_role;
    grant usage,select on all sequences in schema public to service_role;
    create table ot_test.clock(now_at timestamptz);
    insert into ot_test.clock values('2026-10-07T00:00:00Z');
    create function ot_test.clock_timestamp() returns timestamptz language sql volatile as 'select now_at from ot_test.clock';
    grant usage on schema ot_test to service_role; grant select on ot_test.clock to service_role; grant execute on function ot_test.clock_timestamp() to service_role;
  `);
  await db.query('insert into auth.users(id) values($1)',[admin]);
  await db.query('insert into public.admins(user_id) values($1)',[admin]);
  for(let n=1;n<=8;n++){
    await db.query('insert into auth.users(id) values($1)',[uid(n)]);
    await db.query('insert into public.members(id,name,role,auth_user_id) values($1,$2,$3,$4)',[n,'fixture-'+n,n<=7?'운영진':'모임원',uid(n)]);
  }
  const migration=await readFile(new URL('../supabase/migrations/20261007010721_ot_room_private_invites.sql',import.meta.url),'utf8');
  await db.exec(migration);checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007040802_ot_accounts_and_member_privacy.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007042424_member_schedule_access.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007043043_public_activity_compatibility.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007080215_signup_profile_and_audio.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007085406_public_signup_approval_notifications.sql',import.meta.url),'utf8'));checks++;
  await db.exec(`create table public.live_participants(event_id bigint,name text);create table public.live_results(event_id bigint,results jsonb);
    create table public.busking_setlist_slots(id bigint primary key,event_id bigint);create table public.busking_setlist_slot_songs(id bigint,slot_id bigint);
    alter table public.live_results enable row level security;create policy "legacy public results" on public.live_results for select to anon,authenticated using(true);
    alter table public.busking_setlist_slots enable row level security;create policy "legacy public slots" on public.busking_setlist_slots for select to anon,authenticated using(true);
    alter table public.busking_setlist_slot_songs enable row level security;create policy "legacy public songs" on public.busking_setlist_slot_songs for select to anon,authenticated using(true);
    create view public.live_vote_breakdown as select lr.event_id,e.title from public.live_results lr join public.events e on e.id=lr.event_id;
    create view public.live_event_points as select p.event_id,e.title from public.live_participants p join public.events e on e.id=p.event_id;
    create view public.live_point_hall_of_fame as with expanded as(select lr.event_id,x.item from (live_results lr cross join lateral jsonb_array_elements(lr.results) x(item))) select item->>'name' as name from expanded;
    grant select on public.live_participants,public.live_results,public.busking_setlist_slots,public.busking_setlist_slot_songs,public.live_vote_breakdown,public.live_event_points,public.live_point_hall_of_fame to anon,authenticated;`);
  await db.exec(await readFile(new URL('../supabase/migrations/20261007095538_public_archive_and_member_birthdays.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007095552_signup_reservations_and_pin_login.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261008012032_signup_result_and_operator_notifications.sql',import.meta.url),'utf8'));checks++;
  for(const role of ['anon','authenticated']){await db.exec('set role '+role);await rejects('select * from public.ot_operator_push_deliveries',[],/permission denied/);await db.exec('reset role');}
  assert.equal((await ok('select char_length(invite_token) as length from public.vom_push_invites where id=1')).rows[0].length,64);
  assert.equal((await ok('select invite_id from public.vom_push_subscriptions where id=1')).rows[0].invite_id,1);
  await db.exec('set role anon');await rejects('select * from public.ot_applicant_push_subscriptions',[],/permission denied/);await db.exec('reset role');
  await db.exec('set role authenticated');await rejects('select * from public.ot_applicant_push_subscriptions',[],/permission denied/);await db.exec('reset role');
  assert.equal((await ok('select count(*)::int as count from public.ot_room_operator_access')).rows[0].count,0,'legacy role/account links must not auto-grant OT access');
  // Simulate the explicit administrator grants used by the production UI.
  await db.query('insert into public.ot_room_operator_access(user_id,member_id,granted_by) select auth_user_id,id,$1 from public.members where role=$2',[admin,'운영진']);
  // Install the exact migration first. Only its clock dependency is then replaced
  // locally so the same SQL body can exercise opening/closing boundaries at any hour.
  for(const signature of ['public.vom_ot_finalize_upload(uuid,uuid,text,text,text,text)','public.vom_ot_record_vote(bigint,bigint,text,uuid)','public.vom_ot_finalize_photo(uuid,uuid,text,text)','public.vom_ot_reserve_upload(uuid,uuid,text,text)']){
    const {rows}=await db.query('select pg_get_functiondef($1::regprocedure) as definition',[signature]);
    await db.exec(rows[0].definition.replaceAll('clock_timestamp()','ot_test.clock_timestamp()'));
  }
  const invite='e2c5c72d-631e-4022-b405-2e1e02480533';
  const claim='f492568c-83a0-4e40-84c4-88e073890b05';
  const path='reviews/'+invite+'/'+claim+'.mp4';
  await db.query('insert into public.ot_room_invites(id,token_hash,issued_by,expires_at,upload_claim_id,upload_claimed_at) values($1,$2,$3,$4,$5,$6)',[invite,'a'.repeat(64),admin,'2099-10-09T00:00:00Z',claim,'2026-10-07T00:00:00Z']);
  const args=[invite,claim,'new candidate','somoim nickname',path,'video.mp4'];
  const finalize='select public.vom_ot_finalize_upload($1,$2,$3,$4,$5,$6) as result';
  await db.exec('set role service_role');
  await rejects(finalize,args,/video_missing/);
  await db.exec('reset role');
  await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)', ['ot-review-videos',path,{size:24,mimetype:'video/mp4'}]);
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T09:00:00Z']);
  await db.exec('set role service_role');
  await rejects(finalize,args,/room_closed/);
  assert.equal((await ok('select count(*)::int as count from public.ot_reviews')).rows[0].count,0);
  await db.exec('reset role');
  await db.query('update ot_test.clock set now_at=$1',['2026-10-06T23:59:59Z']);
  await db.exec('set role service_role');
  await rejects(finalize,args,/room_closed/);
  await db.exec('reset role');
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T00:00:00Z']);
  await db.exec('set role service_role');
  await rejects(finalize,[invite,uid(20),...args.slice(2)],/invalid_claim/);
  await rejects(finalize,[invite,null,...args.slice(2)],/invalid_claim/);
  await rejects(finalize,[...args.slice(0,4),'reviews/other/video.mp4','video.mp4'],/invalid_file_path/);
  const reviewId=(await ok(finalize,args)).rows[0].result.id;
  const stored=(await ok('select * from public.ot_reviews where id=$1',[reviewId])).rows[0];
  assert.equal(Date.parse(stored.due_at)-Date.parse(stored.created_at),3*3600000);checks++;
  assert.equal(new Date(stored.created_at).toISOString(),'2026-10-07T00:00:00.000Z');checks++;
  assert.equal(stored.required_majority,4);assert.deepEqual(stored.eligible_operator_ids,[1,2,3,4,5,6,7]);assert.equal(stored.somoim_nickname,'somoim nickname');
  assert.equal((await ok('select review_id,upload_claim_id from public.ot_room_invites where id=$1',[invite])).rows[0].review_id,reviewId);
  await rejects(finalize,args,/already_submitted/);
  const vote='select public.vom_ot_record_vote($1,$2,$3,$4) as result';
  await rejects(vote,[reviewId,2,'APPROVE',uid(1)],/voter_identity_mismatch/);
  await rejects(vote,[reviewId,8,'APPROVE',admin],/operator_required/);
  await ok(vote,[reviewId,1,'APPROVE',uid(1)]);
  await ok(vote,[reviewId,1,'HOLD',uid(1)]);
  assert.equal((await ok('select count(*)::int as count from public.ot_review_votes where review_id=$1',[reviewId])).rows[0].count,1);
  await ok(vote,[reviewId,1,'APPROVE',uid(1)]);
  await ok(vote,[reviewId,2,'APPROVE',uid(2)]);
  await ok(vote,[reviewId,3,'APPROVE',uid(3)]);
  const resolved=(await ok(vote,[reviewId,4,'APPROVE',admin])).rows[0].result;
  assert.equal(resolved.status,'APPROVED');assert.equal(resolved.approval_count,4);
  await rejects(vote,[reviewId,5,'REJECT',uid(5)],/review_resolved/);
  assert.equal((await ok('select count(*)::int as count from public.members')).rows[0].count,8,'voting must not create a member automatically');
  await db.exec('reset role; set role anon');
  await rejects('select * from public.ot_room_invites',[],/permission denied/);
  await rejects('select * from public.ot_room_operator_access',[],/permission denied/);
  await rejects(finalize,args,/permission denied/);
  await db.exec('reset role; set role authenticated');
  await rejects('select * from public.ot_room_invites',[],/permission denied/);
  await rejects(vote,[reviewId,1,'APPROVE',uid(1)],/permission denied/);
  await db.exec('reset role');
  const functions=(await db.query("select proname,prosecdef,proconfig from pg_proc where proname in ('vom_ot_finalize_upload','vom_ot_record_vote')")).rows;
  assert(functions.every(fn=>fn.prosecdef===false));checks++;
  // The same majority transaction must generate exactly one private-linked profile.
  await db.exec('reset role');
  const applicant=uid(40),newInvite=uid(41),accountClaim=uid(42);
  await db.query('insert into auth.users(id) values($1)',[applicant]);
  await db.query('insert into public.ot_room_invites(id,token_hash,issued_by,expires_at,account_claim_id,account_claimed_at) values($1,$2,$3,$4,$5,now())',[newInvite,'c'.repeat(64),admin,'2099-10-09T00:00:00Z',accountClaim]);
  await db.exec('set role service_role');
  await ok('select public.vom_ot_bind_account($1,$2,$3,$4)',[newInvite,accountClaim,applicant,{login_name:'new-vom',candidate_name:'Private legal name',somoim_nickname:'Public nickname',phone:'private-phone',birth_date:'2000-01-01'}]);
  await rejects('select public.vom_ot_bind_account($1,$2,$3,$4)',[newInvite,accountClaim,applicant,{}],/invalid_account_claim/);
  const inserted=(await db.query("insert into public.ot_reviews(candidate_name,somoim_nickname,video_source,video_file_path,due_at,eligible_operator_ids,required_majority) values('Private legal name','Public nickname','FILE','reviews/test/video.mp4',now(),array[1,2,3,4,5,6,7],4) returning id")).rows[0].id;
  await db.query('update public.ot_room_invites set review_id=$1 where id=$2',[inserted,newInvite]);
  for(let n=1;n<=3;n++)await ok(vote,[inserted,n,'APPROVE',admin]);
  assert.equal((await ok('select count(*)::int as count from public.members where auth_user_id=$1',[applicant])).rows[0].count,0);
  await ok(vote,[inserted,4,'APPROVE',admin]);
  const linked=(await ok('select id,name,nickname,role from public.members where auth_user_id=$1',[applicant])).rows[0];
  assert(linked.id>8);assert.equal(linked.name,'Public nickname');assert.equal(linked.role,'모임원');
  assert.equal((await ok('select completed_member_id from public.ot_reviews where id=$1',[inserted])).rows[0].completed_member_id,linked.id);
  await rejects(vote,[inserted,5,'APPROVE',admin],/review_resolved/);
  assert.equal((await ok('select count(*)::int as count from public.members where auth_user_id=$1',[applicant])).rows[0].count,1);
  await db.exec('reset role');
  await db.query("update public.members set phone='other-private-phone',birth_date='1990-01-01',region='private-region' where id=8");
  await db.query("insert into public.events(id,title,event_type,host_note) values(1,'private schedule','OTHER','operator-only'),(2,'public listing','BUSKING','public host announcement'),(3,'VOM OPEN MIC #01','OTHER','public host announcement')");
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[applicant]);await db.exec('set role authenticated');
  assert.deepEqual((await ok('select id from public.members')).rows.map(r=>r.id),[linked.id]);
  const other=(await ok('select birth_date,region from public.members_public where id=8')).rows[0];assert.equal(other.birth_date,null);assert.equal(other.region,null);
  assert.equal((await ok('select phone from public.ot_room_applicants')).rows[0].phone,'private-phone');
  assert.equal((await ok('select count(*)::int as count from public.events')).rows[0].count,3);
  await rejects("update public.ot_room_applicants set member_id=8",[],/permission denied/);
  await rejects("select public.vom_ot_bind_account($1,$2,$3,$4)",[newInvite,accountClaim,applicant,{}],/permission denied/);
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid(50)]);await db.exec('set role authenticated');
  assert.equal((await ok('select count(*)::int as count from public.members_public')).rows[0].count,0);
  assert.equal((await ok('select count(*)::int as count from public.ot_room_applicants')).rows[0].count,0);
  assert.equal((await ok('select count(*)::int as count from public.events')).rows[0].count,0);
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role anon');
  assert.equal((await ok('select count(*)::int as count from public.members')).rows[0].count,0);
  await rejects('select * from public.members_public',[],/permission denied/);
  assert.equal((await ok('select count(*)::int as count from public.events')).rows[0].count,0);
  await db.exec('reset role');await db.exec("update public.events set event_date='2001-01-01' where id in(2,3)");await db.exec('set role anon');
  const publiclyVisible=(await ok('select * from public.events_public')).rows;assert.equal(publiclyVisible.length,2);assert(publiclyVisible.every(r=>r.title!=='private schedule'));assert.equal(publiclyVisible[0].host_note,'public host announcement');
  const display=(await ok('select * from public.members_display limit 1')).rows[0];assert(!('birth_date' in display));assert(!('phone' in display));
  await db.exec('reset role');
  // New signup form: year/job/experience and an owner-bound private photo before audio.
  await db.exec('reset role');
  const audioUser=uid(60),audioInvite=uid(61),audioClaim=uid(62),photoClaim=uid(63);
  await db.query('insert into auth.users(id) values($1)',[audioUser]);
  await db.query('insert into public.ot_room_invites(id,token_hash,issued_by,expires_at,account_claim_id,account_claimed_at) values($1,$2,$3,$4,$5,now())',[audioInvite,'d'.repeat(64),admin,'2099-10-09T00:00:00Z',audioClaim]);
  const newProfile={login_name:'audio-vom',candidate_name:'Private audio name',somoim_nickname:'Audio nickname',birth_year:1995,job:'Private job',busking_experience:0,busking_experience_unit:'COUNT',form_version:2};
  await db.exec('set role service_role');
  await rejects('select public.vom_ot_bind_account($1,$2,$3,$4)',[audioInvite,audioClaim,audioUser,{...newProfile,job:null}],/applicant_required_details/);
  await ok('select public.vom_ot_bind_account($1,$2,$3,$4)',[audioInvite,audioClaim,audioUser,newProfile]);
  await db.exec('reset role');
  const audioPath='reviews/'+audioInvite+'/'+audioClaim+'.m4a',photoPath='profiles/'+audioInvite+'/'+photoClaim+'.jpg';
  await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3),($1,$4,$5)',['ot-review-videos',audioPath,{size:24,mimetype:'audio/mp4'},photoPath,{size:24,mimetype:'image/jpeg'}]);
  await db.query('update public.ot_room_invites set upload_claim_id=$1,upload_claimed_at=now() where id=$2',[audioClaim,audioInvite]);
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T01:00:00Z']);
  await db.exec('set role service_role');
  const audioArgs=[audioInvite,audioClaim,'Forged name','Forged nickname',audioPath,'live.m4a'];
  await rejects(finalize,audioArgs,/photo_required/);
  await db.exec('reset role');
  await db.query('update public.ot_room_invites set upload_claim_id=$1 where id=$2',[photoClaim,audioInvite]);
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T10:00:00Z']);
  await db.exec('set role service_role');
  await rejects('select public.vom_ot_finalize_photo($1,$2,$3,$4)',[audioInvite,audioClaim,photoPath,'me.jpg'],/invalid_photo_claim/);
  await ok('select public.vom_ot_finalize_photo($1,$2,$3,$4)',[audioInvite,photoClaim,photoPath,'me.jpg']);
  await db.exec('reset role');
  await db.query('update public.ot_room_invites set upload_claim_id=$1,upload_claimed_at=now() where id=$2',[audioClaim,audioInvite]);
  await db.exec('set role service_role');
  await rejects(finalize,audioArgs,/room_closed/);
  await db.exec('reset role');await db.query("update public.ot_room_invites set signup_source='PUBLIC' where id=$1",[audioInvite]);await db.exec('set role service_role');
  const reserved=(await ok('select public.vom_ot_reserve_upload($1,$2,$3,$4) as receipt',[audioInvite,audioClaim,audioPath,'live.m4a'])).rows[0].receipt;
  assert.equal(new Date(reserved.scheduled_at).toISOString(),'2026-10-08T00:00:00.000Z');assert.equal((await ok('select status from public.ot_signup_reservations where invite_id=$1',[audioInvite])).rows[0].status,'WAITING');

  await db.exec('reset role');await db.query('update ot_test.clock set now_at=$1',['2026-10-07T01:00:00Z']);await db.exec('set role service_role');
  const audioReview=(await ok(finalize,audioArgs)).rows[0].result.id;
  const audioRow=(await ok('select candidate_name,somoim_nickname,media_kind from public.ot_reviews where id=$1',[audioReview])).rows[0];
  assert.equal(audioRow.media_kind,'AUDIO');assert.equal(audioRow.candidate_name,newProfile.candidate_name);assert.equal(audioRow.somoim_nickname,newProfile.somoim_nickname);
  for(let n=1;n<=4;n++)await ok(vote,[audioReview,n,'APPROVE',admin]);
  assert.equal((await ok('select job from public.members where auth_user_id=$1',[audioUser])).rows[0].job,newProfile.job);
  await db.exec('reset role;set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid(8)]);
  assert.equal((await ok('select * from public.ot_room_applicants where auth_user_id=$1',[audioUser])).rows.length,0);
  await rejects('select public.vom_ot_finalize_photo($1,$2,$3,$4)',[audioInvite,photoClaim,photoPath,'me.jpg'],/permission denied/);
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");
  await db.exec("insert into public.events(id,title,event_type,event_date) values(90,'future private live','VOM LIVE','2099-01-01')");
  await db.exec("insert into public.live_participants values(90,'future member');insert into public.live_results values(90,'[{\"name\":\"future member\"}]');insert into public.busking_setlist_slots values(1,90);insert into public.busking_setlist_slot_songs values(1,1)");
  await db.exec('set role anon');assert.equal((await ok('select count(*)::int as count from public.events_public where id=90')).rows[0].count,0);assert.equal((await ok('select private.vom_can_view_event(90) as visible')).rows[0].visible,false);
  for(const table of ['live_participants','live_results','busking_setlist_slots','busking_setlist_slot_songs','live_vote_breakdown','live_event_points','live_point_hall_of_fame'])assert.equal((await ok('select count(*)::int as count from public.'+table)).rows[0].count,0,table+' must not expose future records');
  await rejects('select * from public.ot_signup_reservations',[],/permission denied/);await rejects('select public.vom_claim_login_attempt($1)',['a'.repeat(64)],/permission denied/);
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid(8)]);await db.exec('set role authenticated');assert.equal((await ok('select count(*)::int as count from public.events_public where id=90')).rows[0].count,1);
  await db.exec('reset role;set role service_role');for(let n=0;n<5;n++)assert.equal((await ok('select public.vom_claim_login_attempt($1) as allowed',['a'.repeat(64)])).rows[0].allowed,true);assert.equal((await ok('select public.vom_claim_login_attempt($1) as allowed',['a'.repeat(64)])).rows[0].allowed,false);
  await db.exec('reset role');
  console.log('PostgreSQL migration and security checks passed:',checks);
}finally{await db.close();}
