import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';

const db=new PGlite();
const admin='00000000-0000-4000-8000-000000000099';
const uid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
let checks=0;
async function ok(sql,params=[]){checks++;return db.query(sql,params);}
async function rejects(sql,params=[],pattern){checks++;await assert.rejects(db.query(sql,params),pattern);}
try{
  // These are schema-only test fixtures based on the inspected production tables.
  // No production data or secrets are copied into this local database.
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create schema storage; create schema ot_test; create schema private;
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema public,auth to anon,authenticated;
    create table auth.users(id uuid primary key);
    create table public.admins(user_id uuid primary key references auth.users(id),created_at timestamptz default now());
    create table public.members(id bigint generated by default as identity primary key,name text not null unique,role text,auth_user_id uuid,is_active boolean default true,
      created_at timestamptz default now(),nickname text,profile_image_url text,joined_at date,birth_date date,region text,gender text,favorite_singers text,join_order integer,job text,phone text);
    create table public.member_account_settings(member_id bigint primary key references public.members(id),must_change_password boolean default false,password_changed_at timestamptz,password_hint text);
    alter table public.members enable row level security;
    create policy "members public profile read" on public.members for select to anon,authenticated using(true);
    create policy "admins can read members" on public.members for select to authenticated using(exists(select 1 from public.admins where user_id=auth.uid()));
    grant select on public.members,public.admins to anon,authenticated;
    create view public.members_public with(security_invoker=true,security_barrier=true) as select id,created_at,name,nickname,profile_image_url,joined_at,is_active,role,birth_date,region,gender,favorite_singers,join_order,job from public.members;
    grant select on public.members_public to anon,authenticated;
    create table public.events(id bigint primary key,created_at timestamptz,title text,event_type text,event_date date,start_time time,end_time time,location text,location_id bigint,image_url text,somoim_apply_enabled boolean,somoim_apply_url text,host_note text,description text,somoim_open_at timestamptz,somoim_open_enabled boolean);
    alter table public.events enable row level security;
    create policy "everyone can read events" on public.events for select to anon,authenticated using(true);
    grant select on public.events to anon,authenticated;
    create table public.ot_reviews(
      id bigint generated by default as identity primary key,created_at timestamptz default now(),updated_at timestamptz default now(),
      candidate_name text not null check(char_length(candidate_name) between 1 and 60),somoim_nickname text not null check(char_length(somoim_nickname) between 1 and 80),
      room_label text not null default 'OT Room',video_source text not null,video_url text,video_file_path text,video_file_name text,memo text,
      status text not null default 'IN_REVIEW' check(status in ('IN_REVIEW','APPROVED','REJECTED')),
      due_at timestamptz not null,eligible_operator_ids bigint[] not null,required_majority smallint not null check(required_majority>0),created_by uuid,resolved_at timestamptz,
      check((video_source='LINK' and video_url is not null and video_file_path is null) or (video_source='FILE' and video_file_path is not null and video_url is null))
    );
    create table public.ot_review_votes(
      id bigint generated by default as identity primary key,created_at timestamptz default now(),updated_at timestamptz default now(),
      review_id bigint not null references public.ot_reviews(id) on delete cascade,voter_member_id bigint not null references public.members(id),
      decision text not null check(decision in ('APPROVE','REJECT','HOLD')),unique(review_id,voter_member_id)
    );
    create table storage.buckets(id text primary key,public boolean not null);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text,metadata jsonb);
    insert into storage.buckets values('ot-review-videos',false);
    grant usage on schema public,auth,storage to service_role;
    grant all on all tables in schema public,auth,storage to service_role;
    grant usage,select on all sequences in schema public to service_role;
    create table ot_test.clock(now_at timestamptz);
    insert into ot_test.clock values('2026-10-07T00:00:00Z');
    create function ot_test.clock_timestamp() returns timestamptz language sql volatile as 'select now_at from ot_test.clock';
    grant usage on schema ot_test to service_role; grant select on ot_test.clock to service_role; grant execute on function ot_test.clock_timestamp() to service_role;
  `);
  await db.query('insert into auth.users(id) values($1)',[admin]);
  await db.query('insert into public.admins(user_id) values($1)',[admin]);
  for(let n=1;n<=8;n++){
    await db.query('insert into auth.users(id) values($1)',[uid(n)]);
    await db.query('insert into public.members(id,name,role,auth_user_id) values($1,$2,$3,$4)',[n,'fixture-'+n,n<=7?'운영진':'모임원',uid(n)]);
  }
  const migration=await readFile(new URL('../supabase/migrations/20261007010721_ot_room_private_invites.sql',import.meta.url),'utf8');
  await db.exec(migration);checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007040802_ot_accounts_and_member_privacy.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007042424_member_schedule_access.sql',import.meta.url),'utf8'));checks++;
  await db.exec(await readFile(new URL('../supabase/migrations/20261007043043_public_activity_compatibility.sql',import.meta.url),'utf8'));checks++;
  assert.equal((await ok('select count(*)::int as count from public.ot_room_operator_access')).rows[0].count,0,'legacy role/account links must not auto-grant OT access');
  // Simulate the explicit administrator grants used by the production UI.
  await db.query('insert into public.ot_room_operator_access(user_id,member_id,granted_by) select auth_user_id,id,$1 from public.members where role=$2',[admin,'운영진']);
  // Install the exact migration first. Only its clock dependency is then replaced
  // locally so the same SQL body can exercise opening/closing boundaries at any hour.
  for(const signature of ['public.vom_ot_finalize_upload(uuid,uuid,text,text,text,text)','public.vom_ot_record_vote(bigint,bigint,text,uuid)']){
    const {rows}=await db.query('select pg_get_functiondef($1::regprocedure) as definition',[signature]);
    await db.exec(rows[0].definition.replaceAll('clock_timestamp()','ot_test.clock_timestamp()'));
  }
  const invite='e2c5c72d-631e-4022-b405-2e1e02480533';
  const claim='f492568c-83a0-4e40-84c4-88e073890b05';
  const path='reviews/'+invite+'/'+claim+'.mp4';
  await db.query('insert into public.ot_room_invites(id,token_hash,issued_by,expires_at,upload_claim_id,upload_claimed_at) values($1,$2,$3,$4,$5,$6)',[invite,'a'.repeat(64),admin,'2099-10-09T00:00:00Z',claim,'2026-10-07T00:00:00Z']);
  const args=[invite,claim,'new candidate','somoim nickname',path,'video.mp4'];
  const finalize='select public.vom_ot_finalize_upload($1,$2,$3,$4,$5,$6) as result';
  await db.exec('set role service_role');
  await rejects(finalize,args,/video_missing/);
  await db.exec('reset role');
  await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)', ['ot-review-videos',path,{size:24,mimetype:'video/mp4'}]);
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T09:00:00Z']);
  await db.exec('set role service_role');
  await rejects(finalize,args,/room_closed/);
  assert.equal((await ok('select count(*)::int as count from public.ot_reviews')).rows[0].count,0);
  await db.exec('reset role');
  await db.query('update ot_test.clock set now_at=$1',['2026-10-06T23:59:59Z']);
  await db.exec('set role service_role');
  await rejects(finalize,args,/room_closed/);
  await db.exec('reset role');
  await db.query('update ot_test.clock set now_at=$1',['2026-10-07T00:00:00Z']);
  await db.exec('set role service_role');
  await rejects(finalize,[invite,uid(20),...args.slice(2)],/invalid_claim/);
  await rejects(finalize,[invite,null,...args.slice(2)],/invalid_claim/);
  await rejects(finalize,[...args.slice(0,4),'reviews/other/video.mp4','video.mp4'],/invalid_file_path/);
  const reviewId=(await ok(finalize,args)).rows[0].result.id;
  const stored=(await ok('select * from public.ot_reviews where id=$1',[reviewId])).rows[0];
  assert.equal(stored.required_majority,4);assert.deepEqual(stored.eligible_operator_ids,[1,2,3,4,5,6,7]);assert.equal(stored.somoim_nickname,'somoim nickname');
  assert.equal((await ok('select review_id,upload_claim_id from public.ot_room_invites where id=$1',[invite])).rows[0].review_id,reviewId);
  await rejects(finalize,args,/already_submitted/);
  const vote='select public.vom_ot_record_vote($1,$2,$3,$4) as result';
  await rejects(vote,[reviewId,2,'APPROVE',uid(1)],/voter_identity_mismatch/);
  await rejects(vote,[reviewId,8,'APPROVE',admin],/operator_required/);
  await ok(vote,[reviewId,1,'APPROVE',uid(1)]);
  await ok(vote,[reviewId,1,'HOLD',uid(1)]);
  assert.equal((await ok('select count(*)::int as count from public.ot_review_votes where review_id=$1',[reviewId])).rows[0].count,1);
  await ok(vote,[reviewId,1,'APPROVE',uid(1)]);
  await ok(vote,[reviewId,2,'APPROVE',uid(2)]);
  await ok(vote,[reviewId,3,'APPROVE',uid(3)]);
  const resolved=(await ok(vote,[reviewId,4,'APPROVE',admin])).rows[0].result;
  assert.equal(resolved.status,'APPROVED');assert.equal(resolved.approval_count,4);
  await rejects(vote,[reviewId,5,'REJECT',uid(5)],/review_resolved/);
  assert.equal((await ok('select count(*)::int as count from public.members')).rows[0].count,8,'voting must not create a member automatically');
  await db.exec('reset role; set role anon');
  await rejects('select * from public.ot_room_invites',[],/permission denied/);
  await rejects('select * from public.ot_room_operator_access',[],/permission denied/);
  await rejects(finalize,args,/permission denied/);
  await db.exec('reset role; set role authenticated');
  await rejects('select * from public.ot_room_invites',[],/permission denied/);
  await rejects(vote,[reviewId,1,'APPROVE',uid(1)],/permission denied/);
  await db.exec('reset role');
  const functions=(await db.query("select proname,prosecdef,proconfig from pg_proc where proname in ('vom_ot_finalize_upload','vom_ot_record_vote')")).rows;
  assert(functions.every(fn=>fn.prosecdef===false));checks++;
  // The same majority transaction must generate exactly one private-linked profile.
  await db.exec('reset role');
  const applicant=uid(40),newInvite=uid(41),accountClaim=uid(42);
  await db.query('insert into auth.users(id) values($1)',[applicant]);
  await db.query('insert into public.ot_room_invites(id,token_hash,issued_by,expires_at,account_claim_id,account_claimed_at) values($1,$2,$3,$4,$5,now())',[newInvite,'c'.repeat(64),admin,'2099-10-09T00:00:00Z',accountClaim]);
  await db.exec('set role service_role');
  await ok('select public.vom_ot_bind_account($1,$2,$3,$4)',[newInvite,accountClaim,applicant,{login_name:'new-vom',candidate_name:'Private legal name',somoim_nickname:'Public nickname',phone:'private-phone',birth_date:'2000-01-01'}]);
  await rejects('select public.vom_ot_bind_account($1,$2,$3,$4)',[newInvite,accountClaim,applicant,{}],/invalid_account_claim/);
  const inserted=(await db.query("insert into public.ot_reviews(candidate_name,somoim_nickname,video_source,video_file_path,due_at,eligible_operator_ids,required_majority) values('Private legal name','Public nickname','FILE','reviews/test/video.mp4',now(),array[1,2,3,4,5,6,7],4) returning id")).rows[0].id;
  await db.query('update public.ot_room_invites set review_id=$1 where id=$2',[inserted,newInvite]);
  for(let n=1;n<=3;n++)await ok(vote,[inserted,n,'APPROVE',admin]);
  assert.equal((await ok('select count(*)::int as count from public.members where auth_user_id=$1',[applicant])).rows[0].count,0);
  await ok(vote,[inserted,4,'APPROVE',admin]);
  const linked=(await ok('select id,name,nickname,role from public.members where auth_user_id=$1',[applicant])).rows[0];
  assert(linked.id>8);assert.equal(linked.name,'Public nickname');assert.equal(linked.role,'모임원');
  assert.equal((await ok('select completed_member_id from public.ot_reviews where id=$1',[inserted])).rows[0].completed_member_id,linked.id);
  await rejects(vote,[inserted,5,'APPROVE',admin],/review_resolved/);
  assert.equal((await ok('select count(*)::int as count from public.members where auth_user_id=$1',[applicant])).rows[0].count,1);
  await db.exec('reset role');
  await db.query("update public.members set phone='other-private-phone',birth_date='1990-01-01',region='private-region' where id=8");
  await db.query("insert into public.events(id,title,event_type,host_note) values(1,'private schedule','OTHER','operator-only'),(2,'public listing','BUSKING','public host announcement'),(3,'VOM OPEN MIC #01','OTHER','public host announcement')");
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[applicant]);await db.exec('set role authenticated');
  assert.deepEqual((await ok('select id from public.members')).rows.map(r=>r.id),[linked.id]);
  const other=(await ok('select birth_date,region from public.members_public where id=8')).rows[0];assert.equal(other.birth_date,null);assert.equal(other.region,null);
  assert.equal((await ok('select phone from public.ot_room_applicants')).rows[0].phone,'private-phone');
  assert.equal((await ok('select count(*)::int as count from public.events')).rows[0].count,3);
  await rejects("update public.ot_room_applicants set member_id=8",[],/permission denied/);
  await rejects("select public.vom_ot_bind_account($1,$2,$3,$4)",[newInvite,accountClaim,applicant,{}],/permission denied/);
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid(50)]);await db.exec('set role authenticated');
  assert.equal((await ok('select count(*)::int as count from public.members_public')).rows[0].count,0);
  assert.equal((await ok('select count(*)::int as count from public.ot_room_applicants')).rows[0].count,0);
  assert.equal((await ok('select count(*)::int as count from public.events')).rows[0].count,0);
  await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role anon');
  assert.equal((await ok('select count(*)::int as count from public.members')).rows[0].count,0);
  await rejects('select * from public.members_public',[],/permission denied/);
  assert.equal((await ok('select count(*)::int as count from public.events')).rows[0].count,0);
  const publiclyVisible=(await ok('select * from public.events_public')).rows;assert.equal(publiclyVisible.length,2);assert(publiclyVisible.every(r=>r.title!=='private schedule'));assert.equal(publiclyVisible[0].host_note,'public host announcement');
  const display=(await ok('select * from public.members_display limit 1')).rows[0];assert(!('birth_date' in display));assert(!('phone' in display));
  await db.exec('reset role');
  console.log('PostgreSQL migration and security checks passed:',checks);
}finally{await db.close();}
